name             'role-mongodb-replicaset1'
maintainer       'Stephen Van Zee'
maintainer_email 'svanzee@caringbridge.org'
license          'All rights reserved'
description      'Installs/Configures role-mongodb-replicaset1'
long_description 'Installs/Configures role-mongodb-replicaset1'
version          '0.1.1'

depends 'mongodb', '0.16.2'
depends 'yum'
